### ISSUE TITLE
[Feature Request] Central creative plugin

### ISSUE THREAD

**Issue by yusshu** [unnamed/creative#11]
Create a subproject which would be a server plugin to manage and unify the server's resource-pack. The plugin should support as many platforms as it can (Paper, Minestom, Velocity, etc.).

Some ideas I have for the plugin:
- There would be an event called at the server start to let other plugins register/add their resources. Like:
```java
interface ResourcePackGenerateEvent {
    
    // Plugins can add their resources to this
    // (mutable) ResourcePack instance
    ResourcePack resourcePack();

}
```

- The plugin could "export" the generated resource-pack to a third-party server like [MCPacks](https://mc-packs.net/), or host it locally using the (existing) `creative-server` subproject. That would be configurable
- The plugin could load existing resources, these resources would be manually specified by a server administrator. These resources could be located at the plugin folder, like `/plugins/creative/initial-resources/`

These ideas are possible now since creative 0.6.0-SNAPSHOT
The goal is to create a plugin that would be used in almost every public server that supports resource-pack. See it as the "Vault" but for servers that use resource-packs

**Comment by yusshu** [comment]
> the biggest problem i can see with this is conflicting resources, especially when dealing with replacing vanilla ones, what should happen when a resource is in /initial-resources/ but then a plugin also wants to replace the same resource?

We would **deserialize** them *(new in 0.6.0-SNAPSHOT)*, add them to the ResourcePack before the `ResourcePackGenerateEvent` and let plugins check if a resource exists, for example

```
class MyPluginResourcePackGenerateListener implements EventListener<ResourcePackGenerateEvent> {
  
    @Override
    public void handle(ResourcePackGenerateEvent event) {
        PackMeta packMeta = event.packMeta();
        if (packMeta == null) {
            event.packMeta(9, "Default description");
        } else {
            // colorize description
            event.packMeta(
                packMeta.format(),
                replaceAmpersandBySectionSignSmartly(packMeta.description())
            );
        }
    }
  
}
```

**Comment by yusshu** [comment]
> for ideas youre free to look at my [resources plugin](https://github.com/dev-hydrogen/resources), licensed as mit personally i would really like a "credits" system implemented where all plugins that add resources can also add a "credit" of their own to a file in the resource pack

Thank you for the resources plugin,
and, the credits system could be implemented yeah

**Comment by dev-hydrogen** [comment]
> > the biggest problem i can see with this is conflicting resources, especially when dealing with replacing vanilla ones, what should happen when a resource is in /initial-resources/ but then a plugin also wants to replace the same resource?
> 
> We would **deserialize** them _(new in 0.6.0-SNAPSHOT)_, add them to the ResourcePack before the `ResourcePackGenerateEvent` and let plugins check if a resource exists, for example
> 
> ```java
> class MyPluginResourcePackGenerateListener implements EventListener<ResourcePackGenerateEvent> {
>   
>     @Override
>     public void handle(ResourcePackGenerateEvent event) {
>         PackMeta packMeta = event.packMeta();
>         if (packMeta == null) {
>             event.packMeta(9, "Default description");
>         } else {
>             // colorize description
>             event.packMeta(
>                 packMeta.format(),
>                 replaceAmpersandBySectionSignSmartly(packMeta.description())
>             );
>         }
>     }
>   
> }
> ```

I believe events are handled in random order, unless the plugin developer sets a specific priority, what should happen in that case?

**Comment by yusshu** [comment]
> I believe event listeners are handled in random order, unless the plugin developer sets a specific priority for the listener, what should happen in that case?

I think we should implement our own event system, similar to LuckPerms
