### ISSUE TITLE
Add ElementRotation.of(Vector3Float origin, Vector3Float angles, boolean rescale)

### ISSUE THREAD

**Issue by MelonHell** [unnamed/creative#39]
it would be very convenient if you added the ability to parse ElementRotation from X, Y and Z like here:
https://github.com/unnamed/hephaestus-engine/blob/6849b23dea8cfbafc74827d54e341aed1a1d2b4a/reader-blockbench/src/main/java/team/unnamed/hephaestus/reader/blockbench/ElementReader.java#L87

**Comment by yusshu** [comment]
I don't think this should be added since it can be misleading (at least during compile-time). Elements can only rotate in a single axis.

**Comment by MelonHell** [comment]
But we enter the rotation angle through Float, and not through Enum, which allows us to enter values in increments other than 22.5, which is just as misleading

**Comment by yusshu** [comment]
This needs more feedback I guess.

@BiConsumer @FixedDev @OcZi

**Comment by FixedDev** [comment]
I don't like the pr. It's less clear than the existing methods. It seems like you can do rotations on more than 1 axis with that.
