### ISSUE TITLE
Fix Custom Unicode characters

### ISSUE THREAD

**Issue by Articdive** [unnamed/creative#4]
When using unicode characters in the extended charset (UTF-16BE), which is what Vanilla Minecraft supports. I attempt to add the char (due to the BE, two chars represent 1 char)
"\uDBBC\uDC01", however unfortuantely it es escaped automatically to "\\\uDBBC\\\uDC01". Could we add an override for \u not to be overriden to \\\u.

**Comment by yusshu** [comment]
Could you provide some sample code or, preferably, open a pull request adding a test on that?

**Comment by Articdive** [comment]
This issue is mostly caused by trying to use UTF-16 chars (which have a low surrogate and high surrogate), because of line 250 in ResourceWriter any (low and high surrogates) UTF-16 character that isn't an ASCII Value or U+2028 or U+2029 will simply be skipped.

In principable to reproduce you can try to give the character 0xFFFFF a custom mapping. (which is a perfectly fine UTF-16 Char that is split into 2 char surrogates.

My solution in my private fork was to simply add the following in the if block on line 250
```
...
 else if (c >= '\u20B0') {
    replacement = String.format("\\u%04x", (int) c);
 } else {
    continue
}
```

**Comment by Septicuss** [comment]
https://gist.github.com/tryashtar/6b2692e11ad46124e5129614fb7856a8

**Comment by yusshu** [comment]
As discussed in the [Discord Server](https://discord.gg/xbba2fy) [here](https://discord.com/channels/683899335405994062/960315518143832114/1056022687035703336), Unicode characters should already work

![image](https://user-images.githubusercontent.com/45738853/211594339-e29fe78f-a94c-4c63-b79a-12517eb7c768.png)


I tested by myself too (Vanilla Minecraft 1.17.1, 1.18.2, 1.19.3):

![image](https://user-images.githubusercontent.com/45738853/211594375-f667c315-5a70-459b-ae5f-7d6ed43c53cc.png)
![image](https://user-images.githubusercontent.com/45738853/211594423-4ab417ee-1b8d-469c-8dfb-28e0528fa3e5.png)
