### ISSUE TITLE
Possibillity to load BBModels

### ISSUE THREAD

**Issue by JonasDevDE** [unnamed/creative#44]
It should be possible to load models from a BBModel so that we can simply add ItemOverrides for BBModels.

**Comment by yusshu** [comment]
I think this could be part of https://github.com/unnamed/unnamed/issues/1

**Comment by JonasDevDE** [comment]
> I think this could be part of [unnamed/unnamed#1](https://github.com/unnamed/unnamed/issues/1)

Oh, haven't seen that. My bad.
