### ISSUE TITLE
The pack metadata should accept a description Component

### ISSUE THREAD

**Issue by yusshu** [unnamed/creative#7]
The [PackMeta](https://github.com/unnamed/creative/blob/main/api/src/main/java/team/unnamed/creative/metadata/PackMeta.java#L45) class, which represents the `pack` metadata section in the `pack.mcmeta` file should accept a Minecraft Component as a description, not only a String

See [Resource Pack Wiki in Minecraft Fandom](https://minecraft.fandom.com/wiki/Resource_pack#Contents):

![image](https://user-images.githubusercontent.com/45738853/210006484-d1f57068-5a84-4249-958c-d960308bb43e.png)

Should we include the full [adventure](https://github.com/KyoriPowered/adventure) library to represent the description field as a `Component`? Or maybe just use a JSON string?

**Comment by dev-hydrogen** [comment]
I think its fine for the description to be a String, as long as its documented that it needs to be a serialized Component. I feel like adding adventure would just be unnecessary bloat, but thats just me.

**Comment by yusshu** [comment]
I don't think documentation is enough
Also, it wouldn't be safe at compile-time

**Comment by yusshu** [comment]
Should we depend on adventure?
Almost every platform already has it bundled

**Comment by yusshu** [comment]
Done! (`dev` branch) 13e039c63e6951eb31d3b728450a64ee9a0fa9a1
Now, we depend on Kyori's [adventure](https://github.com/KyoriPowered/adventure)
